### PR TITLE
Implement Register User Modal

### PR DESCRIPTION
**Pull request by saralopezbz**
This pull request implements a modal for user registration in the application. The feature has been developed based on the user story:
**User Story:**
-   **AS** an admin
-   **I WANT** to register a new user
-   **SO THAT** I can create new user accounts 
**Implementation Details:**
-   Created a `RegisterModal` component using `Formik` and `SweetAlert2` for user registration.
-   The modal includes the following fields: Full Name, Surname, Email, Password, Country, and RUT.
-   Implemented form validation to ensure all required fields are filled:
    -   **Name:** Required.
    -   **Surname:** Required.
    -   **Email:** Required, with proper email format validation.
    -   **Password:** Required, must meet the criteria (min 8 characters, 1 uppercase, 1 number, 1 special character).
    -   **Country:** Required, default set to "Chile".
    -   **RUT:** Required, with format validation using `rut-chile`.
-   The role is fixed to "user" as per the requirements.
-   Managed form submission with error handling and validation messages displayed using `SweetAlert2`.
-   Integrated the `RegisterModal` with the `Home` component, allowing the admin to open the modal and register a new user.
**Backend Endpoint Testing:**
-   Tested the following backend endpoint to ensure user registration works as expected:
    -   **Endpoint:** `http://localhost:3000/users/`
{
    "email": "textingg@example.com",
    "password": "Password12*"
}
reate new user accounts with specific roles and permissions.

### CODE REVIEW

**Comment by spancavil** [comment]
Hello Sara! How you doing? I have these observations:

1. There are lots of new libraries used here. Formik RUT and Swal. I prefer that you do not use Swal since it is not fully compatible with React, attached is a warning that the console shows:
image
You can do the following: either not use swal and use custom modals (without any library) or follow the following documentation: https://sweetalert2.github.io/recipe-gallery/sweetalert2-react.html

2. Please remember to separate responsibilities: "validations" in their corresponding folder and also "services" with API calls in their folder. Likewise, error messages should go in the "constants" => messages folder. This makes later escalation easier.

3. Last but not least the API call isn't working because apparently the phone must be sent.

I await for corrections. Thanks.

**Comment by saralopezbz** [comment]
## Refactor Codebase: Structure Improvement and Compatibility Fixes

### Overview:
This PR includes significant refactoring to improve the structure of the codebase and resolve compatibility issues with React. Key changes involve replacing Swal with custom modals, separating concerns by organizing validations, services, and constants into their respective folders, and ensuring all required fields are included in API calls.

### Key Changes:
- **Removed Swal**: Replaced Swal with custom modals due to compatibility issues with React.
- **Validations**: Moved RUT validation to a dedicated `validations` folder.
- **Services**: API calls have been moved to a `services` folder for better organization.
- **Constants**: Introduced a `constants/messages` folder to centralize error message management.
- **API Call Fix**: Ensured the phone field is correctly included in the user registration API call.


Please review the changes and provide feedback or approval.

**Comment by spancavil** [comment]
Hello Sara,
Good job so far! 

I have a couple of observations:
1. Maybe you could fade the bottom of the modal to highlight that the modal was opened
Screenshot from 2024-08-16 10-50-13
2. Also I don't know if the alert will remain or not, or if they will work on it in another task? Please confirm this for me.
Screenshot from 2024-08-16 10-53-40

**Comment by spancavil** [comment]
Nice! Please update this branch in order to merge. Thanks Sara!

**Comment by saralopezbz** [comment]
This pull request includes two key improvements:

Fade Modal Background:

Updated the modal component to include a faded background overlay. This helps to highlight that the modal is open, improving user focus on the modal content.
Custom Notification Modal:

Implemented a custom notification modal for user registration. The notification handles both successful registrations and error cases, ensuring the user receives immediate feedback. The notification is displayed correctly after form submission and can be easily dismissed by the user.

**Comment by spancavil** [comment]
Nice Sara, full documented update.
I still have merge problems.
image

I don't know if you are working on it.

**Comment by saralopezbz** [comment]
Hello Seba, yes, I am working on it. I solve it right away

**Comment by saralopezbz** [comment]
**Conflict Resolution:**

Resolved conflicts in the codebase to ensure smooth integration of recent changes.

**Refactor Notification Handling:**

Refactored the RegisterModal component to improve how error notifications are handled and displayed.
Integrated custom error messages from the backend to provide clearer feedback to users. For instance, if a user attempts to register with an existing RUT or email, they will now see specific, user-friendly messages explaining the issue.
Updated the validationMessages in constants/messages.ts to include these new custom messages.

**Comment by saralopezbz** [comment]
This pull request includes the following changes:

- **Move User Registration Form**: The user registration form has been moved from the Home component to the DashboardAdmin component to better align with the application's structure and user flow.
  
- **Refactor Modal Handling**: Updated the DashboardAdmin component to include the modal for user registration, ensuring that it is properly managed within the admin interface.

**Comment by spancavil** [comment]
Hello Sara! I got this error:
image
And I have this .env:
image
Am I missing something?

**Comment by saralopezbz** [comment]
Hi Seba, 

VITE_BACKEND_URL=http://localhost:3000
VITE_LOGIN_URL=auth/login
VITE_USERS_URL=users

**Comment by spancavil** [comment]
Ok Sara, please update the readme then, because the version is outdated.

It's working the register, but it doesn't close automatically. And also I have to refresh to view the users updated. It would be fine to see the users updated automatically.

Looking forward for corrections!

**Comment by saralopezbz** [comment]
Refresh user view on new user creation

- Auto-refresh the user list in `DashboardAdmin` after a new user is created.
- Updated `RegisterModal` to trigger the refresh upon successful registration.
- Updated `README.md` to reflect the correct environment variables.

**Comment by spancavil** [comment]
Very well!
The toast is missing, informing the user that the user was created correctly, but let's put it in another task, since the toast is a generic component that will be used throughout the app.
We close this task.

**Review by spancavil — APPROVED** [review]

**Pull request merged**
