### PR TITLE
Feature user profile update

### PR DESCRIPTION
**Pull request by gabybot**

### CODE REVIEW

**Comment by spancavil** [comment]
Hello Gaby!
Please add a description of the features of this pull request.

**Comment by gmoyamor** [comment]
Hi Sebastian, the features that have been added are: 1- Dashboard and modal design, 2- Validations for name, email, phone, RUT, etc., 3- Requested functionalities, only certain data can be changed, such as name, last name, phone, etc., except for email and RUT. When the profile is updated, the new changes are immediately shown, it connects to the backend to fetch the data and sends the new ones. Additionally, we decided to leave out the "profile picture" feature since it will be implemented in the future. Thank you.@spancavil

**Comment by spancavil** [comment]
Hello Gaby
I got a couple of import errors:
image
Check it out.

**Comment by sara-rioseco** [comment]
I'll be taking this task from now on, hope to upload everything before today's daily.

**Comment by gmoyamor** [comment]
@spancavil  nuevo commit

**Comment by sara-rioseco** [comment]
After a bunch of hours I think we've got Gabi's code merged and running with our current changes.
There are a couple things not ready yet (editing a regular user info, deleting users from admin dashboard, and fixing a few css details here and there). We'll be doing that tomorrow 😪 
This branch should be up to date with the other PR #16  opened right now, so maybe you could review that one in the meantime @spancavil .

Thanks!

**Comment by spancavil** [comment]
Hi Sara and Gaby.
I am getting this problem:
image
I already reviewed and approved the PR you mentioned.

**Comment by gmoyamor** [comment]
@spancavil  que extraño seba, verificaste bien la rama?

**Comment by sara-rioseco** [comment]
Hello @spancavil!
The dashboard for regular users should be fully functional now. 
We added the edit user and edit password features on the card and fix some css.

**Comment by spancavil** [comment]
Hi girls, good work!

image
 I commented this line and works, but please check that.

Also when I update an user successfully it would be fine to see the updated info (like in admin dashboard)

**Comment by sara-rioseco** [comment]
Regarding the import, I really don't know what is happening cause all of us tried it and it works good.
For some reason you don't have that file called isNameValid.ts but we do. And as you can see below I just did a pull and push
image

**Comment by sara-rioseco** [comment]
Fix problem when updating user info, on regular user dashboard.
Now it should show the updated data immediately.

**Comment by spancavil** [comment]
Fine Sara, please update the branch for merging.
Thanks!

**Comment by sara-rioseco** [comment]
It's done, @spancavil !

**Comment by spancavil** [comment]
Very good! I tried it and works all properly. Congratulations.

**Review by spancavil — APPROVED** [review]

**Pull request merged**
