### PR TITLE
Feature login

### PR DESCRIPTION
**Pull request by sara-rioseco**
Sorry for the long PR. 

Feature login should be working now, with email validation and error handling.
An error message will be displayed accordingly if the login fails or the email is invalid.
For now, if login is successful the user will be redirected to /home route, we'll fix that when we implement route protection in the following days.

Also if you have any advice, suggestion or complementary material regarding project/folder structure for React projects, we'd really appreciate it, cause our folders are starting to get a little messy.

Thanks and have a good evening!

### CODE REVIEW

**Comment by spancavil** [comment]
Hi Sara!
The structure is fine. You used custom hooks that's wonderful. Maybe you could put these custom hooks at "hooks" folder.

To finish checking it I need the environment variables, please add them in the readme, just like you did in the backend readme

**Comment by sara-rioseco** [comment]
> Hi Sara! The structure is fine. You used custom hooks that's wonderful. Maybe you could put these custom hooks at "hooks" folder.
> 
> To finish checking it I need the environment variables, please add them in the readme, just like you did in the backend readme

I added the .env example in the readme!

**Comment by spancavil** [comment]
An eye icon to show password would be fine Sara! For password inputs only.
It works properly.

**Comment by sara-rioseco** [comment]
> An eye icon to show password would be fine Sara! For password inputs only. It works properly.

It's done! 😅

**Comment by spancavil** [comment]
Really nice!

**Review by spancavil — APPROVED** [review]

**Pull request merged**
